addSbtPlugin("com.geirsson"      % "sbt-scalafmt"        % "0.6.6")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"             % "1.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"             % "0.9.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-multi-jvm"       % "0.3.11")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "1.8.0")
addSbtPlugin("me.lessis"         % "bintray-sbt"         % "0.3.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.1.1")
